add Task1-2
ValeryJK/Dotnet_mentoring_intermediate_practice pull request #1
Opened 2024-05-12 11:31 UTC by ValeryJK

2024-05-13 08:47 UTC, D9bolic requested changes

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.API/ActionFilters/ValidationFilterAttribute.cs
> +            }
empty line after the if block

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.API/ActionFilters/ValidationFilterAttribute.cs
> +        public void OnActionExecuting(ActionExecutingContext context)
subprograms(methods and props) shall be separated by empty lines

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.API/ActionFilters/ValidationFilterAttribute.cs
> +            var param = context.ActionArguments.SingleOrDefault(x => x.Value.ToString().Contains("Dto")).Value;
better to use case insensitive comparing

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.API/ActionFilters/ValidationFilterAttribute.cs
> +        public void OnActionExecuted(ActionExecutedContext context) { }
empty lines every where

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/ApiControllerBase.cs
> +        public IActionResult ProcessError(ApiBaseResponse baseResponse)
global filter or middleware for such proposes

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/AuthenticationController.cs
> +            if (!result.Succeeded)
blocks minimization: if (result.Succeeded){ return... }

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/AuthenticationController.cs
> +            return StatusCode(201);
201 shall be base class as method. if not - please use StatusCodes consts list

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/AuthenticationController.cs
> +                return Unauthorized();
braces in if + inversion minimization. if(auth) return OK
про скобочки: безобразно, но единообразно(но по русски тут не отвечай))

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/AuthenticationController.cs
> +        public AuthenticationController(IServiceManager service) => _service = service;
fields and ctor - empty line

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/EventsController.cs
> +        /// <returns></returns>
or remove or fill return block. But better to use swagger XML docs

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/EventsController.cs
> +            var events = await _services.EventService.GetAllEventsAsync(trackChanges: false);
trackChanges desicion shall be on service side only, controller is translator and error rrhandler.

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/AuthenticationController.cs
> +                return Unauthorized();
Bad request(404) looks like better status code. Unouthrize = you are trying to rich restricted resource

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/AuthenticationController.cs
> +        [HttpPost("register")]
Action is strictly probithed in REST.
registration = POST verb
login = Authentication/User POST verb
or smth like that

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/OrdersController.cs
> +                return NotFound("Cart not found or empty");
braces. But better tenar + .net 6 feature( is null)

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/OrdersController.cs
> +            if (payload is null)
em. is null))

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/OrdersController.cs
> +                return BadRequest("Payload is empty");
bracers

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/OrdersController.cs
> +            if (!success)
tenar operator

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/OrdersController.cs
> +        [HttpPut("{cartId}/book")]
patch or post verb instead of action in route

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/OrdersController.cs
> +            if (!success)
Not sure that you need transient event id, if you are using surrogate keys(id)

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/PaymentsController.cs
> +        public async Task<IActionResult> CompletePayment(Guid paymentId)
I believe I saw totally the same controller somewhere... complete and failed are actions - 1, 2 - why do you need 2 separate actions?

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/PaymentsController.cs
> +            if (!success)
please avoid inversions + tenar operator

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/VenuesController.cs
> +            catch (KeyNotFoundException)
DRY violation - AOP via ASP.NET filters

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.API/Extensions/ExceptionMiddlewareExtensions.cs
> +                    if (contextFeature != null)
Block minimization. contextFeature  is null

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.API/Program.cs
> +            builder.Host.UseNLog();
Serilog = standard defacto

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.API/Program.cs
> +            // Add services to the container.
comments shall be deleted

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.Common/DTO/SeatDto.cs
> +
extra line

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.Core.Service/ServiceRegistration.cs
> +
extra line

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.Core.Service/Services/AuthenticationService.cs
> +            return claims;
line after the block

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.Core.Service/Services/AuthenticationService.cs
> +            var keyBytes = new byte[32];
magic number

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.Core.Service/Services/Interfaces/ILoggerManager.cs
> +
line

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.Core.Service/Services/LoggerManager.cs
> +    public class LoggerManager : ILoggerManager
on non PL/API layer better to use logging interface only. In our case: Microsoft.Loggin.Abstraction

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.Core.Service/Services/PaymentService.cs
> +                return default;
or better to raise exception in such cases? and translate it to the 404

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.Core.Service/Services/PaymentService.cs
> +            payment.Status = PaymentStatus.Failed;
for such propouses better to use so virtual(as part of your DB) wallet and check money on it

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.Core.Service/Services/ServiceManager.cs
> +    public sealed class ServiceManager : IServiceManager
as you are using DI better to avoid Unit Of Work/Factory like implementations and just to inject necessary services in their consumers directly

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.Data/DataContext/MainDBContext.cs
> +
extra line

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.Data/DataContext/MainDBContext.cs
> +
extra line

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.Data/Repositories/CartItemRepository.cs
> +
extra line

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.Data/Repositories/CartRepository.cs
> +
extra line

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.Data/Repositories/IRepositoryBase.cs
> +        IQueryable<TEntity> FindByCondition(Expression<Func<TEntity, bool>> expression,
as you are exposing IQuerible you don't need FindByCondition method excplicitly

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.Data/Repositories/IRepositoryManager.cs
> +    public interface IRepositoryManager
same as for services

2024-05-13 08:47 UTC, D9bolic commented on src/EventBookSystem.Data/Repositories/Interfaces/IPaymentRepository.cs
> +        Task<IEnumerable<Payment>> GetAllPaymentsAsync(bool trackChanges);
looks pretty the same as IRepo interface. Please consider

2024-05-13 08:47 UTC, D9bolic commented on test/EventBookSystem.Api.IntegrationTests/UnitTest1.cs
> +        public void Test1()
???

2024-05-13 08:47 UTC, D9bolic commented on test/EventBookSystem.Api.IntegrationTests/UnitTest1.cs
> +        public void Test1()
Please close:
Services and Controllers via unit tests
Repo non generic methods(with includes) via integration tests
Services and controllers shall be covered via integration tests with next option: 1 positive primary way(all validations fine)

2024-05-13 08:47 UTC, D9bolic commented on test/EventBookSystem.Tests/EventBookSystem.Tests.csproj
> +    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
Fluent Assertion as asserting tool

2024-05-18 11:43 UTC, ValeryJK commented on src/EventBookSystem.API/ActionFilters/ValidationFilterAttribute.cs
> +            }
done

2024-05-18 11:44 UTC, ValeryJK commented on src/EventBookSystem.API/ActionFilters/ValidationFilterAttribute.cs
> +        public void OnActionExecuting(ActionExecutingContext context)
done

2024-05-18 11:45 UTC, ValeryJK commented on src/EventBookSystem.API/ActionFilters/ValidationFilterAttribute.cs
> +        public void OnActionExecuted(ActionExecutedContext context) { }
done

2024-05-18 11:45 UTC, ValeryJK commented on src/EventBookSystem.API/Controllers/AuthenticationController.cs
> +        public AuthenticationController(IServiceManager service) => _service = service;
done

2024-05-18 11:46 UTC, ValeryJK commented on src/EventBookSystem.API/Program.cs
> +            // Add services to the container.
done

2024-05-18 11:46 UTC, ValeryJK commented on src/EventBookSystem.Common/DTO/SeatDto.cs
> +
done

2024-05-18 11:46 UTC, ValeryJK commented on src/EventBookSystem.Core.Service/ServiceRegistration.cs
> +
done

2024-05-18 11:47 UTC, ValeryJK commented on src/EventBookSystem.Core.Service/Services/AuthenticationService.cs
> +            var keyBytes = new byte[32];
done

2024-05-18 11:47 UTC, ValeryJK commented on src/EventBookSystem.Core.Service/Services/Interfaces/ILoggerManager.cs
> +
done

2024-05-18 11:47 UTC, ValeryJK commented on src/EventBookSystem.Data/DataContext/MainDBContext.cs
> +
done

2024-05-18 11:47 UTC, ValeryJK commented on src/EventBookSystem.Data/Repositories/CartItemRepository.cs
> +
done

2024-05-18 11:48 UTC, ValeryJK commented on src/EventBookSystem.Data/Repositories/IRepositoryBase.cs
> +        IQueryable<TEntity> FindByCondition(Expression<Func<TEntity, bool>> expression,
done

2024-05-18 11:48 UTC, ValeryJK commented on test/EventBookSystem.Tests/EventBookSystem.Tests.csproj
> +    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
done

2024-05-18 11:49 UTC, ValeryJK commented on src/EventBookSystem.API/ActionFilters/ValidationFilterAttribute.cs
> +            var param = context.ActionArguments.SingleOrDefault(x => x.Value.ToString().Contains("Dto")).Value;
done

2024-05-18 11:50 UTC, ValeryJK commented on src/EventBookSystem.Core.Service/Services/AuthenticationService.cs
> +            return claims;
done

2024-05-18 11:50 UTC, ValeryJK commented on src/EventBookSystem.Data/DataContext/MainDBContext.cs
> +
done

2024-05-18 13:59 UTC, ValeryJK commented on src/EventBookSystem.API/Controllers/AuthenticationController.cs
> +            return StatusCode(201);
done

2024-05-18 13:59 UTC, ValeryJK commented on src/EventBookSystem.API/Controllers/EventsController.cs
> +            var events = await _services.EventService.GetAllEventsAsync(trackChanges: false);
done

2024-05-18 14:00 UTC, ValeryJK commented on src/EventBookSystem.Data/Repositories/CartRepository.cs
> +
done

2024-05-18 14:31 UTC, ValeryJK commented on src/EventBookSystem.API/Controllers/AuthenticationController.cs
> +            if (!result.Succeeded)
done

2024-05-18 14:31 UTC, ValeryJK commented on src/EventBookSystem.API/Controllers/AuthenticationController.cs
> +                return Unauthorized();
done

2024-05-18 14:32 UTC, ValeryJK commented on src/EventBookSystem.API/Controllers/OrdersController.cs
> +                return NotFound("Cart not found or empty");
done

2024-05-18 14:32 UTC, ValeryJK commented on src/EventBookSystem.API/Controllers/OrdersController.cs
> +                return BadRequest("Payload is empty");
done

2024-05-18 14:32 UTC, ValeryJK commented on src/EventBookSystem.API/Controllers/PaymentsController.cs
> +            if (!success)
done

2024-05-18 14:35 UTC, ValeryJK commented on src/EventBookSystem.API/Controllers/OrdersController.cs
> +            if (payload is null)
done

2024-05-18 14:36 UTC, ValeryJK commented on src/EventBookSystem.API/Controllers/OrdersController.cs
> +            if (!success)
done

2024-05-18 15:00 UTC, ValeryJK commented on src/EventBookSystem.API/Controllers/EventsController.cs
> +        /// <returns></returns>
done

2024-05-18 15:57 UTC, ValeryJK commented on src/EventBookSystem.API/Program.cs
> +            builder.Host.UseNLog();
done

2024-05-18 15:57 UTC, ValeryJK commented on src/EventBookSystem.API/Extensions/ExceptionMiddlewareExtensions.cs
> +                    if (contextFeature != null)
done

2024-05-18 15:58 UTC, ValeryJK commented on src/EventBookSystem.API/Controllers/OrdersController.cs
> +        [HttpPut("{cartId}/book")]
done

2024-05-18 15:58 UTC, ValeryJK commented on src/EventBookSystem.API/Controllers/AuthenticationController.cs
> +        [HttpPost("register")]
done

2024-05-18 17:14 UTC, ValeryJK commented on src/EventBookSystem.Core.Service/Services/ServiceManager.cs
> +    public sealed class ServiceManager : IServiceManager
done

2024-05-18 17:15 UTC, ValeryJK commented on src/EventBookSystem.Data/Repositories/IRepositoryManager.cs
> +    public interface IRepositoryManager
done

2024-05-18 17:41 UTC, ValeryJK commented on src/EventBookSystem.Data/Repositories/Interfaces/IPaymentRepository.cs
> +        Task<IEnumerable<Payment>> GetAllPaymentsAsync(bool trackChanges);
done

2024-05-18 18:36 UTC, ValeryJK commented on src/EventBookSystem.API/Controllers/PaymentsController.cs
> +        public async Task<IActionResult> CompletePayment(Guid paymentId)
done

2024-05-18 19:18 UTC, ValeryJK commented on src/EventBookSystem.Core.Service/Services/PaymentService.cs
> +                return default;
done

2024-05-18 19:18 UTC, ValeryJK commented on src/EventBookSystem.Core.Service/Services/LoggerManager.cs
> +    public class LoggerManager : ILoggerManager
done

2024-05-18 19:19 UTC, ValeryJK commented on src/EventBookSystem.API/Controllers/ApiControllerBase.cs
> +        public IActionResult ProcessError(ApiBaseResponse baseResponse)
done

2024-05-19 20:14 UTC, ValeryJK commented on test/EventBookSystem.Api.IntegrationTests/UnitTest1.cs
> +        public void Test1()
done

2024-05-19 20:16 UTC, ValeryJK commented on src/EventBookSystem.Core.Service/Services/PaymentService.cs
> +            payment.Status = PaymentStatus.Failed;
I got it. Only simplified

2024-05-20 10:28 UTC, D9bolic requested changes

2024-05-20 10:28 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/EventsController.cs
> +            catch (KeyNotFoundException)
DRY violation. Please use ExceptionFitler to translate

2024-05-20 10:28 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/OrdersController.cs
> +            if (paymentId == null)
is null

2024-05-20 10:28 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/VenuesController.cs
> +            if (venueDto == null)
is null + braces

2024-05-20 10:28 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/VenuesController.cs
> +            if (!ModelState.IsValid)
braces

2024-05-20 10:28 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/VenuesController.cs
> +                return BadRequest(ModelState);
braces

2024-05-20 10:28 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/VenuesController.cs
> +            catch (KeyNotFoundException)
Catch still here. Issue was not fixed. Please use exception/error fitler

2024-05-20 10:28 UTC, D9bolic commented on src/EventBookSystem.API/Extensions/ExceptionMiddlewareExtensions.cs
> +                    if (contextFeature != null)
is not null

2024-05-20 10:28 UTC, D9bolic commented on src/EventBookSystem.Common/EventBookSystem.Common.csproj
> +    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
please use build.props file for the static analyzing setup

2024-05-20 10:28 UTC, D9bolic commented on src/EventBookSystem.Core.Service/Services/AuthenticationService.cs
> +                await _userManager.AddToRolesAsync(user, roles: userForRegistration.Roles);
braces

2024-05-20 10:28 UTC, D9bolic commented on src/EventBookSystem.Core.Service/Services/AuthenticationService.cs
> +                _logger.LogWarning($"{nameof(ValidateUser)}: Authentication failed. Wrong user name or password.");
braces

2024-05-20 10:28 UTC, D9bolic commented on src/EventBookSystem.Core.Service/Services/CartService.cs
> +            if (cartItem != null)
is not null

2024-05-20 10:28 UTC, D9bolic commented on src/EventBookSystem.Core.Service/Services/EventService.cs
> +                throw new KeyNotFoundException("Event not found.");
braces

2024-05-20 10:28 UTC, D9bolic commented on src/EventBookSystem.Core.Service/Services/VenueService.cs
> +                throw new KeyNotFoundException("Venue not found.");
braces

2024-05-20 10:28 UTC, D9bolic commented on src/EventBookSystem.Data/EventBookSystem.Data.csproj
> +  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
Please add sonar analizer packages as static analizer

2024-05-20 10:28 UTC, D9bolic commented on src/EventBookSystem.Data/Repositories/EventRepository.cs
> +
extra line

2024-05-20 10:28 UTC, D9bolic commented on test/EventBookSystem.IntegrationTests/EventBookSystem.IntegrationTests.csproj
> +    <IsTestProject>true</IsTestProject>
formating

2024-05-20 12:39 UTC, ValeryJK commented on src/EventBookSystem.API/Controllers/EventsController.cs
> +            catch (KeyNotFoundException)
done

2024-05-20 12:40 UTC, ValeryJK commented on src/EventBookSystem.API/Controllers/VenuesController.cs
> +            if (venueDto == null)
done

2024-05-20 12:41 UTC, ValeryJK commented on src/EventBookSystem.API/Controllers/VenuesController.cs
> +            if (!ModelState.IsValid)
done

2024-05-20 12:41 UTC, ValeryJK commented on src/EventBookSystem.API/Controllers/VenuesController.cs
> +                return BadRequest(ModelState);
done

2024-05-20 12:41 UTC, ValeryJK commented on test/EventBookSystem.IntegrationTests/EventBookSystem.IntegrationTests.csproj
> +    <IsTestProject>true</IsTestProject>
done

2024-05-20 12:44 UTC, ValeryJK commented on src/EventBookSystem.Data/EventBookSystem.Data.csproj
> +  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
done

2024-05-20 12:45 UTC, ValeryJK commented on src/EventBookSystem.API/Controllers/VenuesController.cs
> +            catch (KeyNotFoundException)
done

2024-05-20 13:20 UTC, ValeryJK commented on src/EventBookSystem.Common/EventBookSystem.Common.csproj
> +    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
done

2024-05-20 13:21 UTC, ValeryJK commented on src/EventBookSystem.Core.Service/Services/AuthenticationService.cs
> +                await _userManager.AddToRolesAsync(user, roles: userForRegistration.Roles);
done

2024-05-20 13:21 UTC, ValeryJK commented on src/EventBookSystem.Core.Service/Services/AuthenticationService.cs
> +                _logger.LogWarning($"{nameof(ValidateUser)}: Authentication failed. Wrong user name or password.");
done

2024-05-20 13:21 UTC, ValeryJK commented on src/EventBookSystem.Core.Service/Services/CartService.cs
> +            if (cartItem != null)
done

2024-05-20 13:21 UTC, ValeryJK commented on src/EventBookSystem.API/Extensions/ExceptionMiddlewareExtensions.cs
> +                    if (contextFeature != null)
done

2024-05-20 15:06 UTC, merged