feature/Task-4  Implemented caching logic for Event resource
ValeryJK/Dotnet_mentoring_intermediate_practice pull request #4
Opened 2024-05-22 18:26 UTC by ValeryJK

2024-05-24 06:36 UTC, D9bolic requested changes

2024-05-24 06:36 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/EventsController.cs
> +            if (!_cache.TryGetValue(cacheKey, out IEnumerable<EventDto>? events))
please use [GetOrCreateAsync]

(https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.memory.cacheextensions.getorcreateasync?view=net-8.0#microsoft-extensions-caching-memory-cacheextensions-getorcreateasync-1(microsoft-extensions-caching-memory-imemorycache-system-object-system-func((microsoft-extensions-caching-memory-icacheentry-system-threading-tasks-task((-0))))))

2024-05-24 06:36 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/EventsController.cs
> +                    .SetSlidingExpiration(TimeSpan.FromMinutes(5));
1) magic number
2) Shall be configurable via appsetting json
3) Service layer looks like better solution for the caching logic

2024-05-24 06:36 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/EventsController.cs
> +        [ResponseCache(Duration = 60, Location = ResponseCacheLocation.Client, NoStore = false)]
Duration as const

2024-05-24 06:36 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/EventsController.cs
> +            var cacheKey = "AllEvents";
magic number - to const

2024-05-24 06:36 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/EventsController.cs
> +            await InvalidateEventCache();
part of service scenario

2024-05-24 06:36 UTC, D9bolic commented on src/EventBookSystem.API/Controllers/EventsController.cs
> +            _cache.Remove("AllEvents");
whay is it task?

2024-05-26 13:28 UTC, ValeryJK commented on src/EventBookSystem.API/Controllers/EventsController.cs
> +            if (!_cache.TryGetValue(cacheKey, out IEnumerable<EventDto>? events))
done

2024-05-26 13:28 UTC, ValeryJK commented on src/EventBookSystem.API/Controllers/EventsController.cs
> +                    .SetSlidingExpiration(TimeSpan.FromMinutes(5));
done

2024-05-26 13:28 UTC, ValeryJK commented on src/EventBookSystem.API/Controllers/EventsController.cs
> +        [ResponseCache(Duration = 60, Location = ResponseCacheLocation.Client, NoStore = false)]
done

2024-05-26 13:29 UTC, ValeryJK commented on src/EventBookSystem.API/Controllers/EventsController.cs
> +            var cacheKey = "AllEvents";
done

2024-05-26 13:29 UTC, ValeryJK commented on src/EventBookSystem.API/Controllers/EventsController.cs
> +            await InvalidateEventCache();
done

2024-05-26 13:29 UTC, ValeryJK commented on src/EventBookSystem.API/Controllers/EventsController.cs
> +            _cache.Remove("AllEvents");
done

2024-05-27 06:59 UTC, merged