Added  pessimistic and optimistic concurrency strategy
ValeryJK/Dotnet_mentoring_intermediate_practice pull request #5
Opened 2024-05-24 00:47 UTC by ValeryJK

2024-05-24 06:42 UTC, D9bolic commented on src/EventBookSystem.Core.Service/Services/CartService.cs
> +            try
in both cases we relly on the database constraints only, that is not good. My suggestion is to use sync construction for such proposes extra abstraction based on concurrent dictionary + dispose implementation based on seat id to do code DB agnostic

2024-05-24 06:42 UTC, D9bolic requested changes

2024-05-24 06:42 UTC, D9bolic commented on src/EventBookSystem.Core.Service/Services/CartService.cs
> +            try
in both cases we relly on the database constraints only, that is not good. My suggestion is to use sync construction for such proposes extra abstraction based on concurrent dictionary + dispose implementation based on seat id to do code DB agnostic

2024-05-24 06:43 UTC, D9bolic requested changes

2024-05-24 06:43 UTC, D9bolic commented on src/EventBookSystem.Core.Service/Services/CartService.cs
> +            try
same

2024-05-24 06:47 UTC, D9bolic requested changes

2024-05-24 06:47 UTC, D9bolic commented on src/EventBookSystem.Core.Service/Services/CartService.cs
> +                    if (item.Seat.Status == SeatStatus.Booked || item.Seat.Status == SeatStatus.Sold)
not enough for the concurent requests.
Also even sync construction will work only if we don't have horizontal scaling. 
In case of horizontal scalin it shall be distributed(such as status change + check during add to cart action, or distributed monitor, that usually is a pain)

2024-05-26 19:37 UTC, ValeryJK commented on src/EventBookSystem.Core.Service/Services/CartService.cs
> +            try
done

2024-05-26 19:38 UTC, ValeryJK commented on src/EventBookSystem.Core.Service/Services/CartService.cs
> +                    if (item.Seat.Status == SeatStatus.Booked || item.Seat.Status == SeatStatus.Sold)
done

2024-05-26 19:38 UTC, ValeryJK commented on src/EventBookSystem.Core.Service/Services/CartService.cs
> +            try
done

2024-05-27 07:04 UTC, merged